export const ACTIVITY_TYPE_UNIT_MOCKED = [
  { activityType: 'Electricity', unit: 'kWh' },
  { activityType: 'Natural Gas', unit: 'm³' },
  { activityType: 'Heating Oil', unit: 'liters' },
  { activityType: 'Coal', unit: 'kg' },
  { activityType: 'Company Vehicles - Gasoline', unit: 'km' },
  { activityType: 'Company Vehicles - Diesel', unit: 'km' },
  { activityType: 'Business Travel - Air (Short Haul)', unit: 'passenger-km' },
  { activityType: 'Business Travel - Air (Long Haul)', unit: 'passenger-km' },
  { activityType: 'Business Travel - Rail', unit: 'passenger-km' },
  { activityType: 'Shipping - Road Freight', unit: 'ton-km' },
  { activityType: 'Water Supply', unit: 'm³' },
  { activityType: 'Wastewater Treatment', unit: 'm³' },
  { activityType: 'Landfill Waste', unit: 'kg' },
  { activityType: 'Recycled Paper', unit: 'kg' },
  { activityType: 'Recycled Plastic', unit: 'kg' },
  { activityType: 'Refrigerant R410A Leakage', unit: 'kg' },
  { activityType: 'Refrigerant R134a Leakage', unit: 'kg' },
  { activityType: 'Data Center Usage', unit: 'kWh' },
  { activityType: 'Cloud Services', unit: 'kWh' },
  { activityType: 'Office Paper Usage', unit: 'kg' },
  { activityType: 'Employee Remote Work', unit: 'hours' },
  { activityType: 'Deforestation', unit: 'hectare' },
  { activityType: 'Fertilizer Use (Nitrogen)', unit: 'kg' },
  { activityType: 'Beef Consumption', unit: 'kg' },
  { activityType: 'Chicken Consumption', unit: 'kg' },
  { activityType: 'Plant-based Food', unit: 'kg' },
  { activityType: 'Cement Production', unit: 'kg' },
  { activityType: 'Steel Production', unit: 'kg' },
  { activityType: 'Aluminum Production', unit: 'kg' },
  { activityType: 'Solar Panel Manufacturing', unit: 'unit' },
];
